FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && \
    pip install -r fastapi/requirements.txt

EXPOSE 8080

CMD ["python", "FastAPI/main.py"]
